location ^~ /themes/ {
    proxy_pass http://ctfd_upstream;
    proxy_hide_header Set-Cookie;
    proxy_hide_header Cache-Control;
    proxy_hide_header Expires;
    add_header Cache-Control $theme_cache_control always;
}
